spring:
  mail:
    host: smtp.qq.com
    username: xxxxxxxx@qq.com
    password: xxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
